language: node_js
node_js:
  - 13

branches:
  only:
  - main

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - ./build_images.sh

after_success:
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push reverse-proxy
  - docker push udagram-api-users
  - docker push udagram-frontend
  - docker push udagram-api-feeds
